In [3]:
# Smart Communication Network Analysis Using Machine Learning
'''1. Project Introduction
This project uses Machine Learning to analyze communication network performance and classify network conditions as Good, Moderate, or Poor.
The analysis will consider parameters such as signal strength, network latency, packet loss, and bandwidth utilization.
 Objectives
- Analyze communication network performance.
- Visualize network parameters using graphs.
- Train a Machine Learning classification model.
- Predict network conditions from input parameters.
- Develop an interactive dashboard to display predictions.'''

'1. Project Introduction\nThis project uses Machine Learning to analyze communication network performance and classify network conditions as Good, Moderate, or Poor.\nThe analysis will consider parameters such as signal strength, network latency, packet loss, and bandwidth utilization.\n Objectives\n- Analyze communication network performance.\n- Visualize network parameters using graphs.\n- Train a Machine Learning classification model.\n- Predict network conditions from input parameters.\n- Develop an interactive dashboard to display predictions.'

In [4]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("All libraries imported successfully!")

All libraries imported successfully!

In [ ]:
%pip install datasets hugging face

Collecting datasets
  Obtaining dependency information for datasets from https://files.pythonhosted.org/packages/24/cc/7f624629846c709ef1c68aa61bfb8d0ae2638cbe265104a1c2f7a630949e/datasets-5.1.0-py3-none-any.whl.metadata
  Downloading datasets-5.1.0-py3-none-any.whl.metadata (24 kB)
Collecting filelock (from datasets)
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/8e/a3/9bc26acff301fe1aaea1cc3d82a1d57e0a34df3e1cadbfa91ac2dbcdde5c/filelock-4.2.0-py3-none-any.whl.metadata
  Downloading filelock-4.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from datasets) (2.4.6)
Requirement already satisfied: pyarrow>=24.0.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from datasets) (26.0.0)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Obtaining dependency information for dill<0.4.2,>=0.3.0 from https://files.pythonhosted.org/packages/1e/77/dc8c558f7593132cf8fefec57c4f60c83b16941c574ac5f619abb3ae7933/dill-0.4.1-py3-none-any.whl.metadata
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.0.3)
Collecting tqdm>=4.66.3 (from datasets)
  Obtaining dependency information for tqdm>=4.66.3 from https://files.pythonhosted.org/packages/a7/03/921a3d3c75785aca9ebfbfcabfbc3a1be12e2ab5265deb026d55a5a3f83e/tqdm-4.70.1-py3-none-any.whl.metadata
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.4 kB ? eta -:--:--
     ------- -------------------------------- 10.2/57.4 kB ? eta -:--:--
     ---------------------------------------- 57.4/57.4 kB 2.9 MB/s eta 0:00:00
Collecting xxhash (from datasets)
  Obtaining dependency information for xxhash from https://files.pythonhosted.org/packages/aa/02/f9413d94fae43cec6d1a74c4f12156c6f4a7f5fd50e1d34defebdee3dec9/xxhash-4.0.1-cp312-cp312-win_amd64.whl.metadata
  Downloading xxhash-4.0.1-cp312-cp312-win_amd64.whl.metadata (18 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Obtaining dependency information for multiprocess<0.70.20 from https://files.pythonhosted.org/packages/71/70/38998b950a97ea279e6bd657575d22d1a2047256caf707d9a10fbce4f065/multiprocess-0.70.19-py312-none-any.whl.metadata
  Downloading multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting fsspec[http]<=2026.7.0,>=2023.1.0 (from datasets)
  Obtaining dependency information for fsspec[http]<=2026.7.0,>=2023.1.0 from https://files.pythonhosted.org/packages/fd/3c/6a2bf344106328fd04963664a60b9bb6496fc25df8e962fcdc1367285fb9/fsspec-2026.7.0-py3-none-any.whl.metadata
  Downloading fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<3.0,>=1.31.0 (from datasets)
  Obtaining dependency information for huggingface-hub<3.0,>=1.31.0 from https://files.pythonhosted.org/packages/eb/b0/0f7b430fd100b3a3b037fdbb314878200241082e607b3383c63d91a13a72/huggingface_hub-2.2.0-py3-none-any.whl.metadata
  Downloading huggingface_hub-2.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: packaging in c:\users\dell\appdata\roaming\python\python312\site-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from datasets) (6.0.3)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets)
  Obtaining dependency information for aiohttp!=4.0.0a0,!=4.0.0a1 from https://files.pythonhosted.org/packages/ae/ce/1f08114679d49655b30a6e0a29858375c94b82c1de1a0bd0a20c2fee8b02/aiohttp-3.14.5-cp312-cp312-win_amd64.whl.metadata
  Downloading aiohttp-3.14.5-cp312-cp312-win_amd64.whl.metadata (8.5 kB)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (8.5.0)
Collecting hf-xet<2.0.0,>=1.6.0 (from huggingface-hub<3.0,>=1.31.0->datasets)
  Obtaining dependency information for hf-xet<2.0.0,>=1.6.0 from https://files.pythonhosted.org/packages/4d/59/b35106dfa71b6eef605dc88bd038fe99c7f86fb132a15b60d0bf2f235b2c/hf_xet-1.7.0-cp38-abi3-win_amd64.whl.metadata
  Downloading hf_xet-1.7.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx2<3,>=2.0.0 (from huggingface-hub<3.0,>=1.31.0->datasets)
  Obtaining dependency information for httpx2<3,>=2.0.0 from https://files.pythonhosted.org/packages/d8/9c/6fe8931fd9f381042a9e4c7d5a7b4cbf7016b252bec0c99a49fce42c3326/httpx2-2.13.1-py3-none-any.whl.metadata
  Downloading httpx2-2.13.1-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from huggingface-hub<3.0,>=1.31.0->datasets) (4.15.0)
Requirement already satisfied: colorama in c:\users\dell\appdata\roaming\python\python312\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas->datasets) (2026.2)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets)
  Obtaining dependency information for aiohappyeyeballs>=2.5.0 from https://files.pythonhosted.org/packages/71/43/1947f06babed6b3f1d7f38b0c767f52df66bfb2bc10b468c4a7de9eceff2/aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets)
  Obtaining dependency information for aiosignal>=1.4.0 from https://files.pythonhosted.org/packages/fb/76/641ae371508676492379f16e2fa48f4e2c11741bd63c48be4b12a6b09cba/aiosignal-1.4.0-py3-none-any.whl.metadata
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets)
  Obtaining dependency information for frozenlist>=1.1.1 from https://files.pythonhosted.org/packages/b8/af/38e51a553dd66eb064cdf193841f16f077585d4d28394c2fa6235cb41765/frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata
  Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata (21 kB)
Collecting multidict<8.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets)
  Obtaining dependency information for multidict<8.0,>=4.5 from https://files.pythonhosted.org/packages/61/0a/11240e5e7d2e986e288f4a6090f569ad00225b7c2c513d4096b36643f9ab/multidict-7.1.0-cp312-cp312-win_amd64.whl.metadata
  Downloading multidict-7.1.0-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets)
  Obtaining dependency information for propcache>=0.2.0 from https://files.pythonhosted.org/packages/58/7b/6e8ef26f6d510a7916064fec68d55fcbfbdf7eb01e377480d66a122152d8/propcache-0.5.4-cp312-cp312-win_amd64.whl.metadata
  Downloading propcache-0.5.4-cp312-cp312-win_amd64.whl.metadata (25 kB)
Collecting yarl<2.0,>=1.25.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets)
  Obtaining dependency information for yarl<2.0,>=1.25.1 from https://files.pythonhosted.org/packages/bb/cc/51a7b4abf4ac593b8e7eb3794b28e5a35ae26eed8bc04787628d215af82f/yarl-1.25.1-cp312-cp312-win_amd64.whl.metadata
  Downloading yarl-1.25.1-cp312-cp312-win_amd64.whl.metadata (115 kB)
     ---------------------------------------- 0.0/115.0 kB ? eta -:--:--
     -------------------- ------------------ 61.4/115.0 kB 3.2 MB/s eta 0:00:01
     -------------------------------------  112.6/115.0 kB 2.2 MB/s eta 0:00:01
     -------------------------------------- 115.0/115.0 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: anyio>=4.10 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets) (4.14.2)
Collecting httpcore2==2.13.1 (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets)
  Obtaining dependency information for httpcore2==2.13.1 from https://files.pythonhosted.org/packages/09/ba/a4568248771ce81957bfb7cc600264a40fbcda092391ee1c415c50be4bea/httpcore2-2.13.1-py3-none-any.whl.metadata
  Downloading httpcore2-2.13.1-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: idna>=3.18 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets) (3.19)
Collecting truststore>=0.10 (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets)
  Obtaining dependency information for truststore>=0.10 from https://files.pythonhosted.org/packages/51/e9/3a7820be2bb0fe53b6bc9c3be26d3d1158004e4c3ab953aa6840b955b1e9/truststore-0.10.5-py3-none-any.whl.metadata
  Downloading truststore-0.10.5-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: h11>=0.16 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from httpcore2==2.13.1->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-5.1.0-py3-none-any.whl (604 kB)
   ---------------------------------------- 0.0/604.4 kB ? eta -:--:--
   -------- ------------------------------- 122.9/604.4 kB 7.5 MB/s eta 0:00:01
   ------------ --------------------------- 194.6/604.4 kB 2.0 MB/s eta 0:00:01
   --------------------------- ------------ 419.8/604.4 kB 3.3 MB/s eta 0:00:01
   ---------------------------------------  604.2/604.4 kB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 604.4/604.4 kB 2.7 MB/s eta 0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
   ---------------------------------------- 0.0/120.0 kB ? eta -:--:--
   ---------------------------------------- 120.0/120.0 kB 3.5 MB/s eta 0:00:00
Downloading huggingface_hub-2.2.0-py3-none-any.whl (839 kB)
   ---------------------------------------- 0.0/839.9 kB ? eta -:--:--
   ---------------- ---------------------- 358.4/839.9 kB 11.2 MB/s eta 0:00:01
   ----------------------------- ---------- 614.4/839.9 kB 6.5 MB/s eta 0:00:01
   ---------------------------------------  829.4/839.9 kB 5.9 MB/s eta 0:00:01
   ---------------------------------------  839.7/839.9 kB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 839.9/839.9 kB 4.1 MB/s eta 0:00:00
Downloading filelock-4.2.0-py3-none-any.whl (135 kB)
   ---------------------------------------- 0.0/135.0 kB ? eta -:--:--
   ---------------------------------------- 135.0/135.0 kB ? eta 0:00:00
Downloading multiprocess-0.70.19-py312-none-any.whl (150 kB)
   ---------------------------------------- 0.0/150.3 kB ? eta -:--:--
   ---------------------------------------- 150.3/150.3 kB 4.5 MB/s eta 0:00:00
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
   ---------------------------------------- 0.0/80.2 kB ? eta -:--:--
   ---------------------------------------- 80.2/80.2 kB 4.4 MB/s eta 0:00:00
Downloading xxhash-4.0.1-cp312-cp312-win_amd64.whl (37 kB)
Downloading aiohttp-3.14.5-cp312-cp312-win_amd64.whl (506 kB)
   ---------------------------------------- 0.0/506.1 kB ? eta -:--:--
   -------------------- ------------------- 256.0/506.1 kB 7.9 MB/s eta 0:00:01
   -------------------- ------------------- 256.0/506.1 kB 7.9 MB/s eta 0:00:01
   ---------------------------------- ----- 440.3/506.1 kB 3.9 MB/s eta 0:00:01
   ---------------------------------------  501.8/506.1 kB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 506.1/506.1 kB 2.6 MB/s eta 0:00:00
Downloading fsspec-2026.7.0-py3-none-any.whl (206 kB)
   ---------------------------------------- 0.0/206.6 kB ? eta -:--:--
   ------------------------------- -------- 163.8/206.6 kB 4.8 MB/s eta 0:00:01
   ---------------------------------------  204.8/206.6 kB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 206.6/206.6 kB 1.8 MB/s eta 0:00:00
Downloading hf_xet-1.7.0-cp38-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB 5.2 MB/s eta 0:00:01
   ---- ----------------------------------- 0.5/3.8 MB 5.6 MB/s eta 0:00:01
   ------ --------------------------------- 0.7/3.8 MB 4.6 MB/s eta 0:00:01
   -------- ------------------------------- 0.8/3.8 MB 3.9 MB/s eta 0:00:01
   ----------- ---------------------------- 1.1/3.8 MB 4.5 MB/s eta 0:00:01
   ------------- -------------------------- 1.2/3.8 MB 4.2 MB/s eta 0:00:01
   -------------- ------------------------- 1.4/3.8 MB 4.1 MB/s eta 0:00:01
   ---------------- ----------------------- 1.5/3.8 MB 3.9 MB/s eta 0:00:01
   ----------------- ---------------------- 1.7/3.8 MB 3.8 MB/s eta 0:00:01
   ------------------- -------------------- 1.9/3.8 MB 3.8 MB/s eta 0:00:01
   -------------------- ------------------- 2.0/3.8 MB 3.6 MB/s eta 0:00:01
   -------------------- ------------------- 2.0/3.8 MB 3.6 MB/s eta 0:00:01
   -------------------- ------------------- 2.0/3.8 MB 3.6 MB/s eta 0:00:01
   -------------------- ------------------- 2.0/3.8 MB 2.8 MB/s eta 0:00:01
   ----------------------- ---------------- 2.2/3.8 MB 2.9 MB/s eta 0:00:01
   ------------------------- -------------- 2.5/3.8 MB 3.1 MB/s eta 0:00:01
   -------------------------- ------------- 2.5/3.8 MB 3.1 MB/s eta 0:00:01
   --------------------------- ------------ 2.6/3.8 MB 2.9 MB/s eta 0:00:01
   ------------------------------ --------- 2.9/3.8 MB 3.0 MB/s eta 0:00:01
   -------------------------------- ------- 3.1/3.8 MB 3.1 MB/s eta 0:00:01
   ---------------------------------- ----- 3.3/3.8 MB 3.2 MB/s eta 0:00:01
   ------------------------------------- -- 3.6/3.8 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  3.8/3.8 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 3.3 MB/s eta 0:00:00
Downloading httpx2-2.13.1-py3-none-any.whl (95 kB)
   ---------------------------------------- 0.0/95.6 kB ? eta -:--:--
   ---------------------------------------- 95.6/95.6 kB 5.7 MB/s eta 0:00:00
Downloading httpcore2-2.13.1-py3-none-any.whl (83 kB)
   ---------------------------------------- 0.0/83.4 kB ? eta -:--:--
   -------------- ------------------------- 30.7/83.4 kB ? eta -:--:--
   ---------------------------------------- 83.4/83.4 kB 1.6 MB/s eta 0:00:00
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl (44 kB)
   ---------------------------------------- 0.0/44.6 kB ? eta -:--:--
   ---------------------------------------- 44.6/44.6 kB ? eta 0:00:00
Downloading multidict-7.1.0-cp312-cp312-win_amd64.whl (93 kB)
   ---------------------------------------- 0.0/93.8 kB ? eta -:--:--
   ---------------------------------------- 93.8/93.8 kB 5.6 MB/s eta 0:00:00
Downloading propcache-0.5.4-cp312-cp312-win_amd64.whl (46 kB)
   ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
   ---------------------------------------- 46.2/46.2 kB 2.2 MB/s eta 0:00:00
Downloading truststore-0.10.5-py3-none-any.whl (19 kB)
Downloading yarl-1.25.1-cp312-cp312-win_amd64.whl (102 kB)
   ---------------------------------------- 0.0/102.6 kB ? eta -:--:--
   ---------------------------------------- 102.6/102.6 kB 5.8 MB/s eta 0:00:00
Installing collected packages: xxhash, truststore, tqdm, propcache, multidict, hf-xet, fsspec, frozenlist, filelock, dill, aiohappyeyeballs, yarl, multiprocess, httpcore2, aiosignal, httpx2, aiohttp, huggingface-hub, datasets
Successfully installed aiohappyeyeballs-2.7.1 aiohttp-3.14.5 aiosignal-1.4.0 datasets-5.1.0 dill-0.4.1 filelock-4.2.0 frozenlist-1.8.0 fsspec-2026.7.0 hf-xet-1.7.0 httpcore2-2.13.1 httpx2-2.13.1 huggingface-hub-2.2.0 multidict-7.1.0 multiprocess-0.70.19 propcache-0.5.4 tqdm-4.70.1 truststore-0.10.5 xxhash-4.0.1 yarl-1.25.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from datasets import load_dataset
import os
# Create the data folder if it doesn't exist
os.makedirs("data", exist_ok=True)
# Download the dataset directly
dataset = load_dataset(
    "codingkiddo/smartnet-network-incidents",
    split="train"
)
# Convert to Pandas DataFrame
df = dataset.to_pandas()
# Save it as a CSV file
df.to_csv("data/network_data.csv", index=False)
print("Dataset downloaded and saved successfully!")
print("Dataset shape:", df.shape)
print(df.head())

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/2.69k [00:00<?, ?B/s]

c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\DELL\.cache\huggingface\hub\datasets--codingkiddo--smartnet-network-incidents. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\DELL\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  155kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 44.5kB

data/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 44.5kB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/4200 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/900 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/900 [00:00<?, ? examples/s]

Dataset downloaded and saved successfully!
Dataset shape: (4200, 11)
  incident_id             timestamp      device_type  rssi_dbm  \
0  INC-002107  2026-01-17T02:20:00Z           laptop       -79
1  INC-005601  2026-02-12T19:00:00Z         smart_tv       -49
2  INC-003195  2026-01-25T09:46:00Z   gaming_console       -41
3  INC-001527  2026-01-12T16:01:00Z  voice_assistant       -52
4  INC-003969  2026-01-31T07:47:00Z         smart_tv       -42

   channel_utilization_pct  latency_ms  packet_loss_pct  dhcp_failures  \
0                       15          60             1.44              1
1                       40         236             8.97              1
2                       53         406            11.21              1
3                       70         548             7.61              0
4                       62         253            23.87              1

   dns_risk_score                                      incident_text  \
0           0.015  laptop repeatedly disconnects with weak RSSI o...
1           0.139  smart tv reports latency of 236 ms and packet ...
2           0.017  gaming console reports latency of 406 ms and p...
3           0.023  Network quality degradation for voice assistan...
4           0.208  smart tv reports latency of 253 ms and packet ...

          label
0   weak_signal
1  high_latency
2  high_latency
3  high_latency
4  high_latency

In [8]:
# Step 6: Load and inspect the dataset
import pandas as pd
df = pd.read_csv("data/network_data.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nDataset information:")
df.info()

Dataset loaded successfully!
Dataset shape: (4200, 11)

Column names:
['incident_id', 'timestamp', 'device_type', 'rssi_dbm', 'channel_utilization_pct', 'latency_ms', 'packet_loss_pct', 'dhcp_failures', 'dns_risk_score', 'incident_text', 'label']

First 5 rows:

,incident_id,timestamp,device_type,rssi_dbm,channel_utilization_pct,latency_ms,packet_loss_pct,dhcp_failures,dns_risk_score,incident_text,label
0,INC-002107,2026-01-17T02:20:00Z,laptop,-79,15,60,1.44,1,0.015,laptop repeatedly disconnects with weak RSSI o...,weak_signal
1,INC-005601,2026-02-12T19:00:00Z,smart_tv,-49,40,236,8.97,1,0.139,smart tv reports latency of 236 ms and packet ...,high_latency
2,INC-003195,2026-01-25T09:46:00Z,gaming_console,-41,53,406,11.21,1,0.017,gaming console reports latency of 406 ms and p...,high_latency
3,INC-001527,2026-01-12T16:01:00Z,voice_assistant,-52,70,548,7.61,0,0.023,Network quality degradation for voice assistan...,high_latency
4,INC-003969,2026-01-31T07:47:00Z,smart_tv,-42,62,253,23.87,1,0.208,smart tv reports latency of 253 ms and packet ...,high_latency

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 4200 entries, 0 to 4199
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   incident_id              4200 non-null   str
 1   timestamp                4200 non-null   str
 2   device_type              4200 non-null   str
 3   rssi_dbm                 4200 non-null   int64
 4   channel_utilization_pct  4200 non-null   int64
 5   latency_ms               4200 non-null   int64
 6   packet_loss_pct          4200 non-null   float64
 7   dhcp_failures            4200 non-null   int64
 8   dns_risk_score           4200 non-null   float64
 9   incident_text            4200 non-null   str
 10  label                    4200 non-null   str
dtypes: float64(2), int64(4), str(5)
memory usage: 1022.2 KB

In [9]:
# Check missing values
print("Missing values in each column:")
print(df.isnull().sum())
# Check duplicate rows
print("\nNumber of duplicate rows:", df.duplicated().sum())
# Display statistical summary
print("\nStatistical summary:")
display(df.describe(include="all").T)

Missing values in each column:
incident_id                0
timestamp                  0
device_type                0
rssi_dbm                   0
channel_utilization_pct    0
latency_ms                 0
packet_loss_pct            0
dhcp_failures              0
dns_risk_score             0
incident_text              0
label                      0
dtype: int64

Number of duplicate rows: 0

Statistical summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
incident_id,4200,4200,INC-002107,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
timestamp,4200,4200,2026-01-17T02:20:00Z,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
device_type,4200,8,tablet,556,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rssi_dbm,4200.0,NaN,NaN,NaN,-57.966429,14.594807,-98.0,-65.0,-56.0,-47.0,-31.0
channel_utilization_pct,4200.0,NaN,NaN,NaN,43.785,25.573018,0.0,24.0,39.0,55.0,100.0
latency_ms,4200.0,NaN,NaN,NaN,141.208095,184.622423,1.0,39.0,72.0,135.25,904.0
packet_loss_pct,4200.0,NaN,NaN,NaN,3.659755,5.278338,0.0,0.58,1.14,4.48,24.84
dhcp_failures,4200.0,NaN,NaN,NaN,1.794048,3.705549,0.0,0.0,0.0,1.0,15.0
dns_risk_score,4200.0,NaN,NaN,NaN,0.241644,0.290514,0.01,0.072,0.135,0.199,0.99
incident_text,4200,2399,Address assignment problem for tablet: repeate...,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
label,4200,6,dhcp_failure,728,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print("Column names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Column names:
['incident_id', 'timestamp', 'device_type', 'rssi_dbm', 'channel_utilization_pct', 'latency_ms', 'packet_loss_pct', 'dhcp_failures', 'dns_risk_score', 'incident_text', 'label']

First 5 rows:

,incident_id,timestamp,device_type,rssi_dbm,channel_utilization_pct,latency_ms,packet_loss_pct,dhcp_failures,dns_risk_score,incident_text,label
0,INC-002107,2026-01-17T02:20:00Z,laptop,-79,15,60,1.44,1,0.015,laptop repeatedly disconnects with weak RSSI o...,weak_signal
1,INC-005601,2026-02-12T19:00:00Z,smart_tv,-49,40,236,8.97,1,0.139,smart tv reports latency of 236 ms and packet ...,high_latency
2,INC-003195,2026-01-25T09:46:00Z,gaming_console,-41,53,406,11.21,1,0.017,gaming console reports latency of 406 ms and p...,high_latency
3,INC-001527,2026-01-12T16:01:00Z,voice_assistant,-52,70,548,7.61,0,0.023,Network quality degradation for voice assistan...,high_latency
4,INC-003969,2026-01-31T07:47:00Z,smart_tv,-42,62,253,23.87,1,0.208,smart tv reports latency of 253 ms and packet ...,high_latency

In [11]:
print(df.columns.tolist())

['incident_id', 'timestamp', 'device_type', 'rssi_dbm', 'channel_utilization_pct', 'latency_ms', 'packet_loss_pct', 'dhcp_failures', 'dns_risk_score', 'incident_text', 'label']

In [12]:

# Check the target column
print("Unique labels:")
print(df["label"].unique())

print("\nNumber of records in each label:")
print(df["label"].value_counts())

print("\nData types and missing values:")
display(pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum()
}))

Unique labels:
<ArrowStringArray>
[      'weak_signal',      'high_latency',           'healthy',
   'wifi_congestion', 'dns_security_risk',      'dhcp_failure']
Length: 6, dtype: str

Number of records in each label:
label
dhcp_failure         728
dns_security_risk    701
wifi_congestion      698
high_latency         696
healthy              691
weak_signal          686
Name: count, dtype: int64

Data types and missing values:

                        Data Type  Missing Values
incident_id                   str               0
timestamp                     str               0
device_type                   str               0
rssi_dbm                    int64               0
channel_utilization_pct     int64               0
latency_ms                  int64               0
packet_loss_pct           float64               0
dhcp_failures               int64               0
dns_risk_score            float64               0
incident_text                 str               0
label                         str               0

In [13]:
print("Unique labels:")
print(df["label"].unique())

print("\nRecords per label:")
print(df["label"].value_counts())

Unique labels:
<ArrowStringArray>
[      'weak_signal',      'high_latency',           'healthy',
   'wifi_congestion', 'dns_security_risk',      'dhcp_failure']
Length: 6, dtype: str

Records per label:
label
dhcp_failure         728
dns_security_risk    701
wifi_congestion      698
high_latency         696
healthy              691
weak_signal          686
Name: count, dtype: int64

In [14]:

# Step 1: Select input features and target

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib
import os

# Input features available for prediction
numeric_features = [
    "rssi_dbm",
    "channel_utilization_pct",
    "latency_ms",
    "packet_loss_pct",
    "dhcp_failures",
    "dns_risk_score"
]

categorical_features = ["device_type"]
features = numeric_features + categorical_features

X = df[features].copy()
y = df["label"].copy()

# Handle any missing values
for col in numeric_features:
    X[col] = X[col].fillna(X[col].median())

X["device_type"] = X["device_type"].fillna("unknown").astype(str)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Prepare categorical data
preprocessor = ColumnTransformer(
    transformers=[
        ("device", OneHotEncoder(handle_unknown="ignore"),
         categorical_features)
    ],
    remainder="passthrough"
)

# Create the machine learning pipeline
model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        class_weight="balanced"
    ))
])

# Train the model
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)

print("Model training completed!")
print("Training records:", len(X_train))
print("Testing records:", len(X_test))
print("Accuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

Model training completed!
Training records: 3360
Testing records: 840
Accuracy: 99.88 %

Classification Report:
                   precision    recall  f1-score   support

     dhcp_failure       1.00      1.00      1.00       146
dns_security_risk       1.00      1.00      1.00       140
          healthy       1.00      0.99      1.00       138
     high_latency       1.00      1.00      1.00       139
      weak_signal       0.99      1.00      1.00       137
  wifi_congestion       1.00      1.00      1.00       140

         accuracy                           1.00       840
        macro avg       1.00      1.00      1.00       840
     weighted avg       1.00      1.00      1.00       840

In [16]:
import os
import joblib

# Create the model folder if it doesn't exist
os.makedirs("model", exist_ok=True)

# Save the trained model
joblib.dump(model, "model/network_model.pkl")

print("Model saved successfully!")
print("File location: model/network_model.pkl")

Model saved successfully!
File location: model/network_model.pkl